---
- name: "Install base-devel, git, gawk, xclip, ag"
  pacman:
    name: 
      - base-devel
      - git
      - gawk
      - xclip
      - the_silver_searcher
      - feh
      - openssh
      - cmake
      - gcc
      - fontconfig
      - man-db
      - man-pages
      - xorg-server
      - xorg-xinit
      - alacritty
      - wget
    state: present
  become: true
- name: "Generate man pages"
  shell: "mandb"
- name: "Make sure sshd is running"
  systemd:
    state: started
    enabled: true
    name: sshd
  become: true

