---
- name: "Chinese simplified, traditional, japanese, korean and unicode font"
  pacman:
    name: 
      - adobe-source-han-sans-cn-fonts 
      - adobe-source-han-sans-tw-fonts
      - noto-fonts
      - noto-fonts-cjk
      - ttf-droid
    state: present
  become: true

- name: "install nerdfont and emoji font"
  yay:
    name: 
      - nerd-fonts-dejavu-complete
      - noto-fonts-emoji
      - ttf-joypixels
    state: present
